# -*- coding: utf-8 -*-
"""Chunk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqF9udzur93OpjWDdL9-PYPLB1fS5fWa
"""

# input: wiki extxractor file
# output: chunk

!pip install langchain
!pip install langchain-text-splitters

EXTRACTED_DIR = "/content/drive/MyDrive/Wikipedia_Extractor_Nov_25"
OUTPUT_DIR = "/content/drive/MyDrive/Wikipedia_Chunks_Dec_1"

import os
import re
import json
from langchain_text_splitters import RecursiveCharacterTextSplitter

from google.colab import drive
drive.mount('/content/drive')
os.makedirs(OUTPUT_DIR, exist_ok=True)

import traceback

# Regex to capture <doc> sections from WikiExtractor output
DOC_REGEX = re.compile(
    r'<doc id="(.*?)" url="(.*?)" title="(.*?)">\n(.*?)</doc>',
    re.S
)

# Chunker config
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100,
    add_start_index=True,
    separators=["\n\n", "\n", ".", " ", ""],
    strip_whitespace=True,
)

def process_single_file(input_file, output_file):
    """
    Extract <doc> blocks and write chunks as JSONL lines.
    """
    with open(input_file, "r", encoding="utf-8") as f:
        content = f.read()

    docs = DOC_REGEX.findall(content)

    chunk_id = 0

    with open(output_file, "w", encoding="utf-8") as out:
        for (_, _, title, text) in docs:
            section = title
            chunks = text_splitter.split_text(text)

            for chunk in chunks:
                record = {
                    "ID": chunk_id,
                    "Title": title,
                    "Section": section,
                    "Content": chunk
                }
                out.write(json.dumps(record, ensure_ascii=False) + "\n")
                chunk_id += 1

    print(f" Saved {chunk_id} chunks → {output_file}")


print("Starting batch chunking (nested folders with auto-resume)...")

for part_folder in sorted(os.listdir(EXTRACTED_DIR)):
    part_path = os.path.join(EXTRACTED_DIR, part_folder)
    if not os.path.isdir(part_path):
        continue

    print(f"\n Part Folder: {part_folder}")

    # Chunk output mirrors extractor
    part_output_dir = os.path.join(OUTPUT_DIR, part_folder)
    os.makedirs(part_output_dir, exist_ok=True)

    for alpha_folder in sorted(os.listdir(part_path)):
        alpha_path = os.path.join(part_path, alpha_folder)
        if not os.path.isdir(alpha_path):
            continue

        print(f"Subfolder: {alpha_folder}")

        alpha_output_dir = os.path.join(part_output_dir, alpha_folder)
        os.makedirs(alpha_output_dir, exist_ok=True)

        for file in sorted(os.listdir(alpha_path)):
            if not file.startswith("wiki_"):
                continue

            input_file = os.path.join(alpha_path, file)
            output_file = os.path.join(alpha_output_dir, f"{file}.jsonl")

            # Auto-resume
            if os.path.exists(output_file):
                print(f"Skipped (exists): {file}")
                continue

            print(f"➤ Processing: {file}")

            try:
                process_single_file(input_file, output_file)
                print(f"Done: {file}")
            except Exception as e:
                print(f"ERROR on {file}: {e}")
                traceback.print_exc()
                continue  # MOVE TO NEXT FILE

print("ALL DONE!")
print("Chunks stored in:", OUTPUT_DIR)

!du -sh "/content/drive/MyDrive/Wikipedia_Chunks_Dec_1"

import json

path = "/content/drive/MyDrive/Wikipedia_Chunks_Dec_1/part_70/AG/wiki_13.jsonl"

with open(path, "r", encoding="utf-8") as f:
    for i in range(3):
        line = f.readline()

        record = json.loads(line)
        print(f"---- Chunk {i} ----")
        print(json.dumps(record, indent=4, ensure_ascii=False))
        print()