# -*- coding: utf-8 -*-
"""generation_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11p6B6drkzJfkChaPGBiOOS9vZCLbsxfq
"""

!ls -lh /content

!pip install faiss-cpu -q

import faiss
print("FAISS version:", faiss.__version__)

from datasets import load_dataset
import torch, faiss, json, time
import numpy as np
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

# -----------------
# CONFIG
# -----------------
EMBEDDING_MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"
READER_MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
RERANKER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-6-v2"

# 🔹 point to Google Drive (persistent storage)
FAISS_INDEX_FILE = "/content/drive/MyDrive/all-mpnet-base-v2_embedding_index.faiss"
DOCS_FILE = "/content/drive/MyDrive/chunks.json"

# 🔹 results will also be saved permanently
RESULTS_FILE = "/content/drive/MyDrive/all-mpnet-base-v2_rag_eval_results_second_run.jsonl"

INITIAL_K, FINAL_K = 20, 5
SYS_PROMPT = (
    "You are an expert Q&A assistant. Use the following pieces of retrieved "
    "context to answer the user's question concisely. Be concise "
)

# -----------------
# RAG PIPELINE
# -----------------
class RAGPipeline:
    def __init__(self, sys_prompt, embedding_model, reader_model, reranker_model,
                 faiss_index_path, documents, initial_k, final_k):
        self.sys_prompt = sys_prompt
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.initial_k, self.final_k = initial_k, final_k

        print("🔹 Loading models...")
        self.embedder = SentenceTransformer(embedding_model, device=self.device)
        self.reranker = CrossEncoder(reranker_model, device=self.device)

        print("🔹 Loading FAISS index...")
        self.index = faiss.read_index(faiss_index_path)
        self.documents = documents

        print("🔹 Loading reader model...")
        self.tokenizer = AutoTokenizer.from_pretrained(reader_model)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        self.reader = AutoModelForCausalLM.from_pretrained(
            reader_model,
            dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16,
            device_map="auto",
        )
        self.generator = pipeline(
            "text-generation",
            model=self.reader,
            tokenizer=self.tokenizer,
            device_map="auto",
        )

    def _retrieve_batch(self, queries):
        """Vectorized FAISS retrieval for a batch of queries."""
        q_embs = self.embedder.encode(queries, convert_to_numpy=True, batch_size=32, show_progress_bar=False)
        q_embs = q_embs.astype("float32")
        faiss.normalize_L2(q_embs)
        _, idxs = self.index.search(q_embs, self.initial_k)

        # Build a list of retrieved document sets (per query)
        retrieved_docs = []
        for q_idx, doc_idxs in enumerate(idxs):
            init_docs = [self.documents[i] for i in doc_idxs]
            pairs = [(queries[q_idx], d["Content"]) for d in init_docs]
            rerank_scores = self.reranker.predict(pairs)
            top_ids = np.argsort(rerank_scores)[::-1][:self.final_k]
            top_docs = [init_docs[i] for i in top_ids]
            retrieved_docs.append(top_docs)
        return retrieved_docs

    def _format_prompt(self, query, docs):
        ctx = "\n\n".join([f"Doc {i+1}: {d['Content']}" for i, d in enumerate(docs)])
        full = f"{self.sys_prompt}\n\n--- CONTEXT ---\n{ctx}\n\n--- USER QUESTION ---\n{query}"
        msgs = [{"role": "user", "content": full}]
        return self.tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)

    def generate_batch(self, queries, retrieved_docs, max_tokens=256):
        prompts = [self._format_prompt(q, docs) for q, docs in zip(queries, retrieved_docs)]
        outputs = self.generator(prompts, max_new_tokens=max_tokens, batch_size=2, do_sample=True, temperature=0.7)
        preds = [
            o[0]["generated_text"].split(prompts[i])[-1].strip()
            if isinstance(o, list) else o["generated_text"].split(prompts[i])[-1].strip()
            for i, o in enumerate(outputs)
        ]
        return preds

# -----------------
# MAIN — Batched execution with dataset.map
# -----------------
if __name__ == "__main__":
    print("Loading MS MARCO dataset (500 queries)...")
    ds = load_dataset("microsoft/ms_marco", "v1.1", split="validation").select(range(500))

    print(" Loading documents + FAISS index...")
    with open(DOCS_FILE, "r") as f:
        documents = json.load(f)

    rag = RAGPipeline(
        sys_prompt=SYS_PROMPT,
        embedding_model=EMBEDDING_MODEL_NAME,
        reader_model=READER_MODEL_NAME,
        reranker_model=RERANKER_MODEL_NAME,
        faiss_index_path=FAISS_INDEX_FILE,
        documents=documents,
        initial_k=INITIAL_K,
        final_k=FINAL_K,
    )

    print(" Running batched RAG pipeline...")

    BATCH_SIZE = 2
    results = []
    for i in tqdm(range(0, len(ds), BATCH_SIZE)):
        batch = ds[i : i + BATCH_SIZE]
        queries = batch["query"]
        qids = batch["query_id"]
        golds = batch["answers"]

        retrieved_sets = rag._retrieve_batch(queries)
        preds = rag.generate_batch(queries, retrieved_sets)

        # Prepare results immediately
        results = [
            {"query_id": qid, "query": q, "gold": g, "pred": p}
            for qid, q, g, p in zip(qids, queries, golds, preds)
        ]

        # Save this batch right away
        with open(RESULTS_FILE, "a") as f:
            for r in results:
                f.write(json.dumps(r) + "\n")

        # Log progress
        print(f"Saved batch {i//BATCH_SIZE + 1} of {len(ds)//BATCH_SIZE}")



    print(f"Finished — results saved to {RESULTS_FILE}")

from google.colab import files
files.download("/content/drive/MyDrive/all-mpnet-base-v2_rag_gen_results_second_run.jsonl")

import os

old_file_path = "/content/drive/MyDrive/all-mpnet-base-v2_rag_eval_results_second_run.jsonl"
new_file_path = "/content/drive/MyDrive/all-mpnet-base-v2_rag_gen_results_second_run.jsonl"

if os.path.exists(old_file_path):
    os.rename(old_file_path, new_file_path)
    print(f"File successfully renamed from '{old_file_path}' to '{new_file_path}'.")
else:
    print(f"Error: The file '{old_file_path}' does not exist. Please check the original filename.")

old_file_path = "/content/drive/MyDrive/all-mpnet-base-v2_rag_eval_results_second_run.jsonl"
new_file_path = "/content/drive/MyDrive/all-mpnet-base-v2_rag_gen_results_second_run.jsonl"

if os.path.exists(old_file_path):
    os.rename(old_file_path, new_file_path)
    print(f"File successfully renamed from '{old_file_path}' to '{new_file_path}'.")
else:
    print(f"Error: The file '{old_file_path}' does not exist. Please check the original filename.")

"""After renaming, the original file will no longer be available under its old name. If you previously downloaded it, that local copy will retain the old name."""



!head -n 5 "/content/drive/MyDrive/all-mpnet-base-v2_rag_gen_results_second_run.jsonl"



