# -*- coding: utf-8 -*-
"""Wikiextractor_Nov_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4DUd_M1qRtUsArn4NXbmgqAXZZw1bK-
"""

!git clone https://github.com/attardi/wikiextractor.git

!pip install lxml



from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

# 2. Define directories
DUMP_DIR = "/content/drive/MyDrive/Wikipedia dump"
OUTPUT_DIR = "/content/drive/MyDrive/Wikipedia_Extractor_Nov_25"

import os

# Ensure output folder exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 3. List and sort all the dump files
all_files = sorted([
    f for f in os.listdir(DUMP_DIR)
    if f.endswith(".bz2") or f.endswith(".xml")  # adjust if needed
])

print("Found dump files:")
for f in all_files:
    print(" -", f)

import subprocess
import os
from multiprocessing import cpu_count
import warnings
warnings.filterwarnings("ignore")

PROCESSES = str(cpu_count())  # use all CPU cores
print("Using processes:", PROCESSES)

# Sort input files
all_files = sorted(all_files)

for i, filename in enumerate(all_files):
    input_file = os.path.join(DUMP_DIR, filename)

    # Unique folder for each file
    output_subfolder = os.path.join(OUTPUT_DIR, f"part_{i:02d}")
    os.makedirs(output_subfolder, exist_ok=True)

    # AUTO-RESUME CHECK:
    # If this part already has wiki output, skip it
    existing = [
        f for f in os.listdir(output_subfolder)
        if f.startswith("wiki_")
    ]

    if len(existing) > 0:
        print(f"⏭️ Skipping {filename} — already extracted ({len(existing)} files)")
        continue

    print(f"\n🔵 Extracting {filename} → {output_subfolder}")

    pycode = f"""
import sys
sys.path.append('/content/wikiextractor')
sys.argv = [
    'WikiExtractor',
    '--processes', '{PROCESSES}',
    '--no-templates',
    '-o', '{output_subfolder}',
    '{input_file}'
]
import wikiextractor.WikiExtractor as W
W.main()
"""

    cmd = ["python3", "-c", pycode]

    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    for line in process.stderr:
        print(line.strip())

    process.wait()
    print(f"✅ Finished {filename}")

!du -sh "/content/drive/MyDrive/Wikipedia_Extractor_Nov_25"