# -*- coding: utf-8 -*-
"""Wikipedia_RAG_sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaLaCvG4XZA5CYDdCf6cp4gJdrFGhFRE
"""

from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive

from google.colab import files
uploaded = files.upload()

EMBEDDINGS_FILE = "all-mpnet-base-v2_embedding.pkl"



import os
print("Current working directory:", os.getcwd())
print("Embeddings file exists:", os.path.exists(EMBEDDINGS_FILE))



import json
import torch
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pickle
import os
import time

# ======================
# CONFIG
# ======================
EMBEDDING_MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"
READER_MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
RERANKER_MODEL_NAME = "cross-encoder/ms-marco-MiniLM-L-2-v2"

EMBEDDINGS_FILE = "/content/drive/MyDrive/embeddings.pkl"

SYS_PROMPT = (
    "You are an expert Q&A assistant. Use the following pieces of retrieved "
    "context to answer the user's question concisely. "
    "If the answer cannot be found in the context, state that you do not "
    "have enough information, but do not make up an answer."
)

INITIAL_K = 20
FINAL_K = 5

# ======================
# RAG PIPELINE CLASS
# ======================
class RAGPipeline:
    def __init__(self, sys_prompt, documents, embedding_model, reader_model, reranker_model, initial_k, final_k):
        self.initial_k = initial_k
        self.final_k = final_k
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.embedder = SentenceTransformer(embedding_model, device=self.device)
        self.reranker = CrossEncoder(reranker_model, device=self.device)
        self.reader_model = reader_model
        self.documents = documents
        self.contents = [doc['Content'] for doc in documents]
        self.sys_prompt = sys_prompt

        # Check for precomputed embeddings
        if os.path.exists(EMBEDDINGS_FILE):
            print(f"Loading existing embeddings from {EMBEDDINGS_FILE}...")
            self.embeddings = self._load_embeddings()
        else:
            print("No embeddings file found — computing now...")
            self.embeddings = self._embed()

        # Set up tokenizer + model
        self.tokenizer = AutoTokenizer.from_pretrained(reader_model)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.reader = AutoModelForCausalLM.from_pretrained(
            reader_model,
            torch_dtype=torch.bfloat16 if self.device == 'cuda' and torch.cuda.is_bf16_supported() else torch.float16,
            device_map='auto'
        )

        self.generator = pipeline(
            "text-generation",
            model=self.reader,
            tokenizer=self.tokenizer,
            torch_dtype=self.reader.dtype,
            device_map="auto"
        )

    # Create and save embeddings if missing
    def _embed(self):
        embeddings = self.embedder.encode(self.contents, convert_to_tensor=True, device=self.device, show_progress_bar=True)
        with open(EMBEDDINGS_FILE, 'wb') as f:
            pickle.dump(embeddings.cpu(), f)
        print(f"Saved embeddings to {EMBEDDINGS_FILE}")
        return embeddings.to(self.device)

    # Load precomputed embeddings
    def _load_embeddings(self):
        with open(EMBEDDINGS_FILE, 'rb') as f:
            embeddings_cpu = pickle.load(f)
        print("Embeddings loaded successfully.")
        return embeddings_cpu.to(self.device)

    # Retrieve top documents
    def _retrieve(self, query_vector, original_query):
        query_vector_np = query_vector.cpu().numpy().reshape(1, -1)
        embeddings_np = self.embeddings.cpu().numpy()
        sims = cosine_similarity(query_vector_np, embeddings_np)[0]
        initial_indices = np.argsort(sims)[::-1][:self.initial_k]
        initial_info = [self.documents[i] for i in initial_indices]

        pairs = [(original_query, doc['Content']) for doc in initial_info]
        reranked = self.reranker.predict(pairs)
        final_top = np.argsort(reranked)[::-1][:self.final_k]
        final_info = [initial_info[i] for i in final_top]
        return final_info

    # Format the LLM prompt
    def _prompt_format(self, query, final_info):
        context = "\n\n".join([f"Document {i+1}: {doc['Content']}" for i, doc in enumerate(final_info)])
        complete_query = (
            f"{self.sys_prompt}\n\n"
            f"--- CONTEXT ---\n{context}\n\n"
            f"--- USER QUESTION ---\n{query}"
        )
        messages = [{"role": "user", "content": complete_query}]
        prompt = self.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        return prompt

    # Run a query through the full RAG pipeline
    def query(self, query, max_tokens=500):
        print(f"\n Query: {query}")
        start_time = time.time()

        embedded_query = self.embedder.encode(query, convert_to_tensor=True, device=self.device)
        retrieved_info = self._retrieve(embedded_query, query)

        retrieval_time = time.time()
        print(f"Retrieved {len(retrieved_info)} documents in {retrieval_time - start_time:.2f}s:")

        for i, doc in enumerate(retrieved_info):
            print(f"  {i+1}. {doc['Title']} | Snippet: \"{doc['Content'][:80]}...\"")

        prompt = self._prompt_format(query, retrieved_info)
        generation_output = self.generator(
            prompt,
            max_new_tokens=max_tokens,
            pad_token_id=self.tokenizer.eos_token_id,
            do_sample=True,
            temperature=0.7
        )

        full_response = generation_output[0]['generated_text']
        answer = full_response.split(prompt)[-1].strip()

        generation_time = time.time()
        print(f" Generation completed in {generation_time - retrieval_time:.2f}s.")

        return answer


# ======================
# RUN EXAMPLE
# ======================
if __name__ == "__main__":
    with open("/content/drive/MyDrive/chunks.json", 'r') as f:
        documents = json.load(f)

    rag = RAGPipeline(
        sys_prompt=SYS_PROMPT,
        documents=documents,
        embedding_model=EMBEDDING_MODEL_NAME,
        reranker_model=RERANKER_MODEL_NAME,
        reader_model=READER_MODEL_NAME,
        initial_k=INITIAL_K,
        final_k=FINAL_K
    )

    sample_query = "What happened to Louis Desaix after he was recalled from Upper Egypt?"
    print(f"\nFinal Answer:\n{rag.query(sample_query)}")

    sample_query_2 = "Where was Desaix born and who were his parents?"
    print(f"\nFinal Answer:\n{rag.query(sample_query_2)}")

!pip install faiss-cpu -q

!ls /content/drive/MyDrive

# ===============================
# FAISS conversion from pickle
# ===============================

# Workflow
# Text: I am a cat
# Embedding: text become vector I am a cat = [0,1,3,2,4] [0,8,0]
# each model is a different way to represent sentence in vector
# After embedding, store all vectors in a pickle file
# Faiss is just a pickle file optimized for vector calculation
# By vector calculation, that mean operation to check if two vector are close together or not => If their meaning is related
# tensor and numpy: format to store vector
# shape of 2x2 matric is (2,2)  [1,2]
                                [2,3]


import faiss
import pickle
import numpy as np
from google.colab import files

# Path to your saved embeddings file
PICKLE_FILE = "all-mpnet-base-v2_embeddings.pkl"
FAISS_INDEX_FILE = "all-mpnet-base-v2_embedding_index.faiss"

# Load embeddings
print("Loading embeddings from pickle...")
with open(PICKLE_FILE, "rb") as f:
    embeddings = pickle.load(f)

# Some sentence-transformers save as torch tensors → convert to numpy
if hasattr(embeddings, "cpu"):
    embeddings = embeddings.cpu().numpy()

# Ensure float32 for FAISS
embeddings = embeddings.astype("float32")
print(f"Loaded {embeddings.shape[0]} embeddings of dimension {embeddings.shape[1]}")

# Normalize for cosine similarity (inner product index)
faiss.normalize_L2(embeddings)

# Build FAISS index
dim = embeddings.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(embeddings)
print(f" FAISS index built with {index.ntotal} vectors")

# Save to disk
faiss.write_index(index, FAISS_INDEX_FILE)
print(f"Saved FAISS index as {FAISS_INDEX_FILE}")

# Download to your computer
files.download(FAISS_INDEX_FILE)
print(" Downloading index.faiss...")