# -*- coding: utf-8 -*-
"""wikipedia_embedding_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ELh3W9zAgpCA1S4yrUI68CpLlEtiBo0q
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install faiss-cpu

import os, json, torch, pickle
import faiss
import numpy as np
from tqdm import tqdm
from sentence_transformers import SentenceTransformer

BASE_DIR = "/content/drive/MyDrive/Wikipedia_Chunks_Dec_1"

SAVE_DIR = "/content/drive/MyDrive/Wikipedia_Faiss_Dec_7/bge-small-en/optimized"

os.makedirs(SAVE_DIR, exist_ok=True)

FAISS_PATH = f"{SAVE_DIR}/wikipedia.index"
META_PATH  = f"{SAVE_DIR}/metadata.pkl"
UID_PATH   = f"{SAVE_DIR}/uids.pkl"
PROCESSED_PATH = f"{SAVE_DIR}/processed_files.pkl"

DIM = 384
index = None

if os.path.exists(FAISS_PATH):
    print("Loading existing FAISS index...")
    index = faiss.read_index(FAISS_PATH)
else:
    print("Creating new FAISS index...")
    index = faiss.IndexFlatIP(DIM)  # inner product for cosine sim

if os.path.exists(META_PATH):
    metadata = pickle.load(open(META_PATH, "rb"))
else:
    metadata = []

if os.path.exists(UID_PATH):
    uids = pickle.load(open(UID_PATH, "rb"))
else:
    uids = []

if os.path.exists(PROCESSED_PATH):
    processed = pickle.load(open(PROCESSED_PATH, "rb"))
else:
    processed = set()

# Initialize UID counter
if uids:
    start_uid = max(uids) + 1
else:
    start_uid = 0

MODEL_NAME = "BAAI/bge-small-en"
device = "cuda" if torch.cuda.is_available() else "cpu"

model = SentenceTransformer(MODEL_NAME, device=device)
use_amp = True

BATCH_SIZE = 4096  # A100/L4 safe

processed = pickle.load(open(PROCESSED_PATH, "rb"))
print("Processed files count:", len(processed))

# Show a few:
for i, f in enumerate(list(processed)):
    print(i, f)

import pickle, os, shutil, faiss, tempfile

def atomic_pickle_dump(obj, final_path):
    """Write pickle safely by writing to temp file then atomic rename."""
    dir_name = os.path.dirname(final_path)
    fd, tmp_path = tempfile.mkstemp(dir=dir_name)
    os.close(fd)
    try:
        with open(tmp_path, "wb") as f:
            pickle.dump(obj, f, protocol=pickle.HIGHEST_PROTOCOL)
        os.replace(tmp_path, final_path)  # atomic
    except Exception as e:
        print("Atomic pickle save failed:", e)
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def safe_save_faiss(index, final_path):
    """Ensure FAISS index is safely written using temp + rename."""
    dir_name = os.path.dirname(final_path)
    tmp_path = os.path.join(dir_name, "faiss_tmp.index")

    # Write to local tmp file
    faiss.write_index(index, tmp_path)

    # Atomic move (safe even on Google Drive)
    os.replace(tmp_path, final_path)

    os.sync()  # force filesystem sync

def process_jsonl_file(jsonl_path):
    global start_uid, index, metadata, uids

    print("  File:", jsonl_path)
    count_added = 0
    texts = []
    local_meta = []

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                item = json.loads(line.strip())
            except:
                continue

            content = item.get("Content", "").strip()
            if not content:
                continue

            uid = start_uid
            start_uid += 1

            texts.append(content)
            local_meta.append({
                "uid": uid,
                "title": item.get("Title"),
                "section": item.get("Section"),
                "content": item.get("Content")
            })
            uids.append(uid)

            # Batch embed
            if len(texts) >= BATCH_SIZE:
                # embs = model.encode(texts, convert_to_numpy=True,
                #                     normalize_embeddings=True)
                embs = model.encode(
                    texts,
                    batch_size=BATCH_SIZE,
                    device="cuda",
                    convert_to_numpy=True,
                    show_progress_bar=False,
                    normalize_embeddings=True
                )
                index.add(embs.astype(np.float32))
                metadata.extend(local_meta)
                count_added += len(embs)
                texts, local_meta = [], []

    # leftover
    if texts:
        embs = model.encode(texts, convert_to_numpy=True,
                            normalize_embeddings=True)
        index.add(embs.astype(np.float32))
        metadata.extend(local_meta)
        count_added += len(embs)

    return count_added

grand_total = 0

part_folders = sorted(
    d for d in os.listdir(BASE_DIR)
    if os.path.isdir(os.path.join(BASE_DIR, d))
)

for part in part_folders:
    part_path = os.path.join(BASE_DIR, part)

    # -------- SKIP ALREADY PROCESSED PART --------
    if part in processed:
        print(f"\n========== SKIP PART (already done): {part} ==========\n")
        continue

    print(f"\n========== PROCESSING PART: {part} ==========\n")
    total_added_this_part = 0

    # loop AA, AB, AC, ...
    for sub in sorted(os.listdir(part_path)):
        sub_path = os.path.join(part_path, sub)
        if not os.path.isdir(sub_path):
            continue

        # loop wiki_0.jsonl, wiki_1.jsonl, ...
        for fname in sorted(os.listdir(sub_path)):
            if fname.endswith(".jsonl"):
                fp = os.path.join(sub_path, fname)
                total_added_this_part += process_jsonl_file(fp)

    print(f"\n>>> Part {part} finished, added {total_added_this_part} vectors")

    # -------- SAVE ONCE PER PART --------
    safe_save_faiss(index, FAISS_PATH)
    atomic_pickle_dump(metadata, META_PATH)
    atomic_pickle_dump(uids, UID_PATH)

    # mark part as processed
    processed.add(part)
    atomic_pickle_dump(processed, PROCESSED_PATH)

    grand_total += total_added_this_part

print("\n========== ALL DONE ==========")
print("Grand Total vectors embedded:", grand_total)

start_uid = max(uids) + 1 if len(uids) > 0 else 0
print("Starting UID:", start_uid)

index2 = faiss.read_index(FAISS_PATH)
print("Vectors in FAISS file:", index2.ntotal)

meta = pickle.load(open(META_PATH, "rb"))
print("Metadata entries:", len(meta))

# Show a random sample to verify content:
print(meta[50])

uids = pickle.load(open(UID_PATH, "rb"))
print("UID entries:", len(uids))
print("First UID:", uids[0])
print("Last UID:", uids[-1])

processed = pickle.load(open(PROCESSED_PATH, "rb"))
print("Processed files count:", len(processed))

# Show a few:
for i, f in enumerate(list(processed)[:10]):
    print(i, f)