# -*- coding: utf-8 -*-
"""wikipedia_embedding_sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LpzGwSqSNDJVsMZGymOLw1kJSlbIPDTf
"""

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

from sentence_transformers import SentenceTransformer
import pickle, json, torch

EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"
EMBEDDINGS_FILE = "embeddings.pkl"

device = 'cuda' if torch.cuda.is_available() else 'cpu'
embedder = SentenceTransformer(EMBEDDING_MODEL, device=device)

with open("chunks.json", "r") as f:
    documents = json.load(f)
contents = [doc['Content'] for doc in documents]

embeddings = embedder.encode(contents, convert_to_tensor=True, show_progress_bar=True)
pickle.dump(embeddings.cpu(), open(EMBEDDINGS_FILE, "wb"))
print("Embeddings saved to embeddings.pkl")

from google.colab import files
files.download("embeddings.pkl")